"""Pure-logic scaffold renderer for ``m new``.

Given a project name, returns a :class:`Scaffold` carrying every file
to materialise. The renderer is engine-agnostic — no filesystem or env
side effects — so unit tests can verify the generated content against
the formatter and linter without writing to disk.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

_M_NAME_MAX = 8  # M routine-name limit (8 chars; per the language convention)


def derive_routine_name(project_name: str) -> str:
    """Map a project name to a valid M routine name.

    Uppercases, strips non-alphanumeric characters, truncates to 8.
    Raises :class:`ValueError` on empty / leading-digit inputs.
    """
    cleaned = re.sub(r"[^A-Za-z0-9]", "", project_name).upper()
    if not cleaned:
        raise ValueError(f"project name {project_name!r} has no valid M-name characters")
    if cleaned[0].isdigit():
        raise ValueError(
            f"project name {project_name!r} starts with a digit; "
            "M routine names must start with a letter"
        )
    return cleaned[:_M_NAME_MAX]


@dataclass(frozen=True)
class Scaffold:
    project_name: str
    routine_name: str
    files: dict[str, str]


def render_scaffold(project_name: str) -> Scaffold:
    rtn = derive_routine_name(project_name)
    files: dict[str, str] = {
        f"routines/{rtn}.m": _render_routine(rtn),
        f"routines/{rtn}ASRT.m": _render_assert_helper(rtn),
        f"tests/{rtn}TST.m": _render_test(rtn),
        ".m-cli.toml": _render_mcli_toml(),
        ".gitignore": _render_gitignore(),
        "Makefile": _render_makefile(rtn),
        "README.md": _render_readme(project_name, rtn),
    }
    return Scaffold(project_name=project_name, routine_name=rtn, files=files)


# ------------------------------------------------------------- file templates


def _render_routine(rtn: str) -> str:
    """Public entry routine in pythonic-lower style.

    Layout:
      - line 1: top-of-routine label matching the routine name
      - line 2: VistA-style version stub (informational)
      - public extrinsic `greet(name)` returning a friendly greeting
    """
    return (
        f"{rtn} ; @summary  {rtn} -- starter routine generated by m new\n"
        f' ;;1.0;{rtn};;0;Build 1\n'
        ' quit\n'
        ' ;\n'
        'greet(name) ; @summary  $$greet(name) -> friendly greeting\n'
        ' quit "Hello, "_name_"!"\n'
    )


def _render_assert_helper(rtn: str) -> str:
    """Tiny self-contained assertion helper (no m-stdlib dependency).

    Implements the wire protocol m-cli's runner expects:
      ``  PASS  <desc>`` / ``  FAIL  <desc>`` / final ``Results:`` line.
    """
    helper = f"{rtn}ASRT"
    return (
        f"{helper} ; @summary  minimal assertion helper for {rtn}TST\n"
        f' ;;1.0;{rtn};;0;Build 1\n'
        ' quit\n'
        ' ;\n'
        'start(pass,fail) ; @summary  initialise pass/fail counters\n'
        ' set pass=0,fail=0\n'
        ' quit\n'
        ' ;\n'
        'eq(pass,fail,actual,expected,desc) ; @summary  assert equality\n'
        ' if actual=expected do  quit\n'
        ' . set pass=pass+1\n'
        ' . write "  PASS  ",desc,!\n'
        ' set fail=fail+1\n'
        ' write "  FAIL  ",desc,!\n'
        ' write "         expected: ",expected,!\n'
        ' write "         actual:   ",actual,!\n'
        ' quit\n'
        ' ;\n'
        'report(pass,fail) ; @summary  print final results banner\n'
        ' new total\n'
        ' set total=pass+fail\n'
        ' write !,"Results: ",total," tests  ",pass," passed  ",fail," failed",!\n'
        ' if fail=0 write "All tests passed.",! quit\n'
        ' write fail," test(s) FAILED.",!\n'
        ' quit\n'
    )


def _render_test(rtn: str) -> str:
    """Starter test suite. Discovered by `m test` via the `*TST.m` convention."""
    suite = f"{rtn}TST"
    helper = f"{rtn}ASRT"
    return (
        f"{suite} ; @summary  unit tests for {rtn}.m\n"
        f' ;;1.0;{rtn};;0;Build 1\n'
        ' new pass,fail\n'
        f' do start^{helper}(.pass,.fail)\n'
        ' ;\n'
        ' do tGreet(.pass,.fail)\n'
        ' ;\n'
        f' do report^{helper}(pass,fail)\n'
        ' quit\n'
        ' ;\n'
        'tGreet(pass,fail) ;@TEST "$$greet returns Hello, world!"\n'
        ' new actual\n'
        f' set actual=$$greet^{rtn}("world")\n'
        f' do eq^{helper}(.pass,.fail,actual,"Hello, world!","greet")\n'
        ' quit\n'
    )


def _render_mcli_toml() -> str:
    return (
        "# m-cli project config — generated by `m new`.\n"
        "# Modern (pythonic-lower) style: lowercase keywords, full canonical\n"
        '# spellings, one command per line. See ~/projects/m-cli/docs/guide.md.\n'
        "\n"
        "[fmt]\n"
        'rules = "pythonic-lower"\n'
        "\n"
        "[lint]\n"
        'rules = "default"\n'
    )


def _render_gitignore() -> str:
    return (
        "# Build / engine artifacts\n"
        "*.o\n"
        "*.obj\n"
        "\n"
        "# Test / coverage output\n"
        "test-results.tap\n"
        "coverage.lcov\n"
        "coverage.xml\n"
        "junit.xml\n"
        ".m-lint-baseline.json\n"
        "\n"
        "# Python tooling (if you mix m-cli development into the project)\n"
        ".venv/\n"
        "__pycache__/\n"
        "*.pyc\n"
        "\n"
        "# Editor / OS scratch\n"
        ".DS_Store\n"
        ".idea/\n"
        ".vscode/\n"
    )


def _render_makefile(rtn: str) -> str:
    return (
        "# Makefile generated by `m new`.\n"
        "#\n"
        "# Requires `m` (m-cli) on PATH. For projects that pin a specific\n"
        "# m-cli checkout, override:  make M=/path/to/m fmt\n"
        "\n"
        "M ?= m\n"
        "\n"
        ".PHONY: fmt fmt-check lint test coverage check clean\n"
        "\n"
        "fmt:\n"
        "\t$(M) fmt routines tests\n"
        "\n"
        "fmt-check:\n"
        "\t$(M) fmt --check routines tests\n"
        "\n"
        "lint:\n"
        "\t$(M) lint --error-on=error routines tests\n"
        "\n"
        "test:\n"
        "\t$(M) test tests\n"
        "\n"
        "coverage:\n"
        "\t$(M) coverage --routines routines --tests tests\n"
        "\n"
        "check: fmt-check lint test\n"
        "\n"
        "clean:\n"
        "\trm -f routines/*.o tests/*.o test-results.tap coverage.lcov\n"
    )


def _render_readme(project_name: str, rtn: str) -> str:
    return (
        f"# {project_name}\n"
        "\n"
        f"M project scaffolded by `m new {project_name}`.\n"
        "\n"
        "## Layout\n"
        "\n"
        "```\n"
        f"routines/{rtn}.m         — production routine\n"
        f"routines/{rtn}ASRT.m     — local assertion helper\n"
        f"tests/{rtn}TST.m         — unit-test suite\n"
        ".m-cli.toml              — m fmt + m lint config (pythonic-lower)\n"
        "Makefile                 — fmt / lint / test / coverage / check\n"
        "```\n"
        "\n"
        "## Quick start\n"
        "\n"
        "```bash\n"
        "make fmt-check    # verify modern style\n"
        "make lint         # default profile (curated M-MOD)\n"
        "make test         # run unit tests against YottaDB\n"
        "make check        # the full local CI gate\n"
        "```\n"
        "\n"
        "## Notes\n"
        "\n"
        f"- Routine `{rtn}` exports `$$greet(name)` — replace it with your own.\n"
        f"- `{rtn}ASRT` is a tiny in-tree assertion helper so this project has\n"
        "  zero external M dependencies. If you adopt m-stdlib, swap each call\n"
        f"  to `^{rtn}ASRT` for the equivalent on `^STDASSERT`.\n"
        "- The pythonic-lower style is enforced by `m fmt` and `m lint`. See\n"
        "  `~/claude/skills/mumps-modern-style/` for the rule-by-rule reference.\n"
    )
