"""GitHub Actions workflow template for ``m ci init``.

Emits a single workflow file (`.github/workflows/m-ci.yml`) that runs
the four project gates the §6.2 Phase 3a roadmap names: format check,
lint, test, coverage.

The container is the YottaDB base image. The runner clones
``tree-sitter-m`` and ``m-cli`` from GitHub and installs them into a
venv. Adjust the matrix or the install source to taste — this is a
starter, not a vendor lock.
"""

from __future__ import annotations


def render_workflow() -> str:
    """Return the contents of `.github/workflows/m-ci.yml` as a string."""
    return _WORKFLOW


_WORKFLOW = """\
# GitHub Actions workflow generated by `m ci init`.
#
# Runs the four project gates on every push and pull request:
#
#   m fmt --check          — verify modern style is preserved
#   m lint --error-on=fatal — run the configured lint profile
#   m test                  — run *TST.m suites under YottaDB
#   m coverage --format=lcov — emit lcov for upload to Codecov, etc.
#
# Customise:
#   - Pin to a specific YottaDB tag (replace `latest-master`).
#   - Add coverage upload (e.g. codecov/codecov-action@v4).
#   - Pin tree-sitter-m / m-cli to a tag instead of HEAD.

name: m-ci

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  m-ci:
    runs-on: ubuntu-latest
    container:
      image: yottadb/yottadb-base:latest-master
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install Python toolchain
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \\
              python3.12 python3.12-venv git make ca-certificates
          python3.12 -m venv /tmp/venv
          /tmp/venv/bin/pip install --upgrade pip

      - name: Install m-cli
        run: |
          # Clone-and-install: tree-sitter-m must land before m-cli so its
          # local checkout satisfies m-cli's dependency declaration.
          git clone https://github.com/rafael5/tree-sitter-m /tmp/tree-sitter-m
          git clone https://github.com/rafael5/m-cli /tmp/m-cli
          /tmp/venv/bin/pip install /tmp/tree-sitter-m
          /tmp/venv/bin/pip install /tmp/m-cli
          echo "/tmp/venv/bin" >> "$GITHUB_PATH"

      - name: Source YottaDB env
        run: |
          # shellcheck disable=SC1091
          . /opt/yottadb/current/ydb_env_set
          {
              echo "ydb_dist=$ydb_dist"
              echo "ydb_routines=$ydb_routines"
              echo "ydb_gbldir=$ydb_gbldir"
          } >> "$GITHUB_ENV"

      - name: m doctor
        run: m doctor

      - name: m fmt --check
        run: m fmt --check routines tests

      - name: m lint --error-on=fatal
        run: m lint --error-on=fatal routines tests

      - name: m test
        run: m test tests

      - name: m coverage --format=lcov
        run: m coverage --format=lcov --routines routines --tests tests > coverage.lcov

      - name: Upload coverage artefact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage.lcov
          if-no-files-found: warn
"""
